platform :ios, '9.0'

target 'Foodiez' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Foodiez
  pod 'GooglePlaces', '~> 2.4'
  pod 'GoogleMaps', '~> 2.4'

end
